os: linux
sudo: false
language: go

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
    - go get -t -v ./collector/...
