# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/AstroProfundis/sysinfo"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.07"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "v1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[prune]
  go-tests = true
  unused-packages = true
