# Check for reproducible build

name: testbuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master
      - tiup
  push:
    branches:
      - master
      - tiup

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
          - 1.13.x
          - 1.16.x

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Prepare environment
        id: prepare_env
        run: |
          echo ::set-output name=GOROOT::$GOROOT
          echo ::set-output name=GOPATH::$GOPATH

      - name: Check for static build
        run: |
          make clean
          GOROOT=${{ steps.prepare_env.GOROOT }} \
          GOPATH=${{ steps.prepare_env.GOPATH }} \
          PATH=$GOROOT/bin:$PATH \
          BUILD_FLAGS='-trimpath -buildmode=pie' \
          make static

